### ISSUE TITLE
Problem with escaping "<" or ">"   (notably in constraints)

### ISSUE THREAD

**Issue by RichardNeill** [rm-hull/sql_graphviz#12]
The output of this unfortunately doesn't correctly escape the angle-brackets, so if the schema has a constraint-check in it, it fails.

```
$ python3 sql_graphviz.py dump.sql  > graph.dot
$ dot -Tsvg graph.dot > graph.svg
Error: graph.dot: syntax error in line 1051 near ':'

```
This is a rather unhelpful message from dot, because that line 1051 is nowhere near the error!

Here is an example of the kind of line that sql_graphviz emits that is wrong:

`<tr><td bgcolor="grey96" align="left" port="CONSTRAINT"><font face="Times-bold">CONSTRAINT</font>  <font color="#535353">location_users_spot_sanity CHECK (((role <> 'Location'::users_role_enum) OR ((manager_id IS NULL) AND (division_id IS NULL) AND (job_title IS NULL) AND (employee_key IS NULL) AND (ldap_key IS NULL) AND (provenance = 'Local'::users_provenance_enum))))</font></td></tr>`

For now, a fixup for "<>", "<=" and ">=" can be done using sed:

`python3 sql_graphviz.py dump.sql | sed -e 's/<>/\&lt;\&gt;/g' -e 's/<=/\&lt;=/g' -e 's/>=/\&gt;=/g' > graph.dot`

Thanks very much - great tool now I can get it working!

**Comment by rm-hull** [comment]
Could you supply a sample `dump.sql` that demonstrates the error so I can reproduce?

**Comment by rm-hull** [comment]
@RichardNeill pull from master - I have added a fix to allow HTML entities to be converted

**Comment by RichardNeill** [comment]
Thanks. You beat me to it wrt the sample file, but I can confirm that your fix works for me. Thanks very much!

On unrelated notes, it might be worth documenting that this works with both python2.7 or python3, and that "fdp" is an alternative to "dot" which some may prefer.
