### ISSUE TITLE
Table fails to correctly parse these default values and generate dot format

### ISSUE THREAD

**Issue by brainlid** [rm-hull/sql_graphviz#8]
Here is another SQL table that fails to generate a table output.

I've narrowed it down to 2 problems.

1. "welcome_message" is a text field with multi-line text content (markdown format) for a column default value.
2. "steps" is a `jsonb` field type with a default value of `'[]'`.

Both columns are breaking the parsing.

```sql
--
-- PostgreSQL database dump
--


CREATE TABLE public.driver_forms (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    platform character varying(255) NOT NULL,
    reseller_id integer,
    client_id integer,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    online boolean DEFAULT true,
    slug character varying(255) NOT NULL,
    description character varying(255),
    active boolean DEFAULT true NOT NULL,
    welcome_message text DEFAULT '# Welcome!

Thank you for your interest.'::text,
    steps jsonb DEFAULT '[]'::jsonb,
    test_mode boolean DEFAULT false,
    confirmation_mode character varying(255) DEFAULT 'message'::character varying
);

--
-- PostgreSQL database dump complete
--
```

**Comment by brainlid** [comment]
I'm not sure how your parsing works. If it's like a regex, perhaps you can disregard anything from `DEFAULT ...(including new lines)... '::` to the ending text of two semi-colons.

**Comment by rm-hull** [comment]
Yes, you are correct on both counts.. with another small fix, this renders as:

<img width="530" alt="screenshot 2019-02-15 at 08 46 17" src="https://user-images.githubusercontent.com/1915543/52845177-5b1d8b00-30fe-11e9-963d-ca50474ef898.png">

I appreciate the time you are taking to provide this feedback / issues 👍

**Comment by brainlid** [comment]
It appears to be working for me now! Thanks!
